virtualenv:
  system_site_packages: true
language: python
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-nose
install:
  - python setup.py install
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=pyamg
after_success:
  - coveralls
