language: python

sudo: false

python:
  - "2.7"
  - "3.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes pip numpy scipy nose
  - pip install python-coveralls
  - pip install .

script:
  - mkdir cov
  - cd cov
  - nosetests --with-coverage --cover-package=pyamg --logging-level=INFO pyamg
  - ls -ltra

after_success:
  - coveralls debug
