language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
install:
- conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install --yes pip numpy scipy
- pip install pytest pytest-cov
- pip install codecov
- pip install -e .
script:
- pytest --cov=. --cov-report=term
after_success:
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then codecov; fi
deploy:
  provider: pypi
  distributions: bdist_wheel
  on:
    branch: master
    tags: true
  password:
    secure: RAkZ5q6i9+mvlyUftuWF4M5DI85lBotjEOEUZTJGDvr2Llsdq2U/niadKzqBiO92096ge3eJ0eluHX9RRzW2myi6M7RJOTYE4tlEpebLkecm3Xn9M85hlZAorVHRNVct5dQQeKXOEYjIm8QB/2wQoi1K/iJSdxh+/mHarFBMYJQ=
  user:
    secure: HE7U4+hoOhgxTiCjpKqynpLLyPyAS09UEg1hpHZYwkRk79pX10xXx7cvJN9q/V+lL3DyZ8DA42QD2TLj4riLHplC03dF16+L1sb0wYfHLt9cI7Zdzvyv9WUDango/JNKqD3SkM8np7WnPNP4QNZK8K6x4oWoGNcUHrjGcAEdgSg=
