language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes pip numpy scipy
  - pip install pytest pytest-cov
  - pip install python-coveralls
  - pip install -e .

script:
  - pytest --cov=. --cov-report=term

after_success:
  - if [[ $ENV == python=3.5* ]]; then
        coveralls;
    fi
