language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-nose
install:
  # pip install . will run setup and check pip success
  - pip install .
  - pip install coveralls
script:
  #- nosetests pyamg --with-coverage --cover-package=pyamg
  - python test_pyamg_install.py
after_success:
  - coveralls
